### ISSUE TITLE
Improve Synapse event posting performance

### ISSUE THREAD

**Issue by feature** [SerenityEnterprises/SerenityCE#4]
### Issue description
Each time the `EventManager.post` method is called, all the registered listeners' event target class is matched against the class of the `event` being posted. This causes a lot of unnecessary overhead when listeners of different event targets are registered, which will exponentially impact performance for each event posting.

**Comment by char** [comment]
Psuedo-duplicate of #3.

**Comment by char** [comment]
Closed by pull request #5
